### ISSUE TITLE
Message filter deletes IP in application Tickets

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [nullsoepic/liveunderflow#11]
Now normally we would not want people sharing the ip. However when applicants are requested the ip the bot deletes it. It does say “message contains blacklisted phrase” but it would be clearer if tickets were exempt from this blacklist.

**Comment by XeynQ4** [comment]
i think the bot should replace the messages containing the right ips with a reply saying "you sent the correct server/proxy ip" or something like that. that way we can verify if he sent the correct one and there will be no leaks. this could be in all channels, not just the application one

**Comment by ATXLtheAxolotl** [comment]
> i think the bot should replace the messages containing the right ips with a reply saying "you sent the correct server/proxy ip" or something like that. that way we can verify if he sent the correct one and there will be no leaks. this could be in all channels, not just the application one

At that point I feel like it may be a repeat of /check, maybe we could go with one of my previous ideas where if they run /check and get it right it will so say in their tickets.

**Comment by enderschesi** [comment]
Id say just exempting the blacklist from tickets would fine,s since the application can only be seen by people that know the ip already anyway

**Comment by enderschesi** [comment]
The code for removing the ip can be deprecated, as Discord' AutoMod already does that job (and excludes Tickets!)

**Comment by enderschesi** [comment]
w
