### ISSUE TITLE
Add mineflayer for more features.

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [nullsoepic/liveunderflow#3]
Using a combination of [mineflayer](https://github.com/PrismarineJS/mineflayer) and [VIAaaS](https://github.com/ViaVersion/VIAaaS) we can create a bot that can log chat messages, players leaving and joining and list the currently online players in /status.

**Comment by ATXLtheAxolotl** [comment]
I think for the VIAaaS part we should use child processes, that way we don’t have to make some weird bash script that runs them at the same time and also be able to read any console output it makes.

**Comment by nullsoepic** [comment]
Using an api endpoint would be easier but wouldnt be really future proof as the api could go down at any time, thinking of just working on a fork of node-minecraft-protocol and implementing the chat stuff but it will take a while

**Comment by ATXLtheAxolotl** [comment]
bet using node-minecraft-protocol
